/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dibujar(GButton source, GEvent event) { //_CODE_:btndr:906999:
  println("btncal - GButton >> GEvent." + event + " @ " + millis());
 int i = star1.getSelectedIndex();
 int n = star2.getSelectedIndex();
   boolean g = false;
   Estrella a = estrellas.get(i);
   Estrella b = estrellas.get(n);
   if(!(a.relaciones.contains(b) && b.relaciones.contains(a))){
     if(a!=b){
   while(g==false){
   String p = JOptionPane.showInputDialog(null,"Digite la distancia en años luz.");
   if(p!=null){
    int peso = Integer.parseInt(p);
   Arista nueva = new Arista(a.x1,a.y1,b.x1,b.y1,peso);
   a.relaciones.add(b);
   b.relaciones.add(a);
   aristas.add(nueva);
   g = true;
   }else{
     JOptionPane.showMessageDialog(null,"Por favor, digite el valor de la distancia en años luz.");
   }
   }
   }else{
   JOptionPane.showMessageDialog(null,"Debe seleccionar estrellas diferentes.");
   }
   }else{
     JOptionPane.showMessageDialog(null,"Esta relación ya existe.");
   }
   
   
   
  
} //_CODE_:btndr:906999:

public void list1(GDropList source, GEvent event) { //_CODE_:star1:304429:

  println("star1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:star1:304429:

public void list2(GDropList source, GEvent event) { //_CODE_:star2:594256:
  println("star2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:star2:594256:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Space");
  btndr = new GButton(this, 300, 14, 99, 30);
  btndr.setText("Dibujar Arista");
  btndr.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  btndr.addEventHandler(this, "dibujar");
  star1 = new GDropList(this, 11, 20, 90, 69, 2);
  star1.setItems(loadStrings("list_304429"), 0);
  star1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  star1.addEventHandler(this, "list1");
  star2 = new GDropList(this, 199, 19, 90, 275, 10);
  star2.setItems(loadStrings("list_594256"), 0);
  star2.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  star2.addEventHandler(this, "list2");
  label1 = new GLabel(this, 108, 20, 80, 23);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("y");
  label1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label1.setOpaque(false);
  mensaje = new GLabel(this, 459, 19, 80, 20);
  mensaje.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  mensaje.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  mensaje.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton btndr; 
GDropList star1; 
GDropList star2; 
GLabel label1; 
GLabel mensaje; 